name: Generate Python Standalone archives

on:
  workflow_dispatch:

env:
  URL_BASE: "https://github.com/indygreg/python-build-standalone/releases/download/"
  D_DIR: "./build_tools/docker/py_standalone_create/"
  REL_TAG: "20211017"
  CPYTHON_VER: "cpython-3.10.0"

jobs:
  on_linux:
    strategy:
      fail-fast: true
      matrix:
        i: [
          { "cpu": "amd64", "os": "manylinux", "d_tag": "centos:7",
            "link": "x86_64-unknown-linux-gnu-lto-20211017T1616.tar.zst",
            "add_packages": "cffi pillow pillow_heif hexhamming"
          } ,
          { "cpu": "arm64", "os": "manylinux", "d_tag": "centos:7",
            "link": "aarch64-unknown-linux-gnu-lto-20211017T1616.tar.zst",
            "add_packages": "cffi pillow pillow_heif hexhamming"
          } ,
#          { "cpu": "x86_64", "os": "musllinux", "d_tag": "alpine:3.12.9",
#            "link": "",
#            "add_packages": "cffi pillow pillow_heif hexhamming"
#          } ,
#          { "cpu": "arm64", "os": "musllinux", "d_tag": "alpine:3.12.9",
#            "link": "" ,
#            "add_packages": "cffi pillow pillow_heif hexhamming"
#          } ,
        ]
    runs-on: ubuntu-latest
    name: ðŸ â€¢ ${{ matrix.i['cpu'] }} â€¢ ${{ matrix.i['os'] }}

    steps:
      - uses: actions/checkout@v2
      - name: Initializing
        run: |
          mkdir st_pythons
          wget -q ${{ env.URL_BASE }}$REL_TAG/$CPYTHON_VER-${{ matrix.i['link'] }} -O standalone.tar.zst
          wget -q https://github.com/indygreg/python-build-standalone/blob/main/LICENSE -O LICENSE
          echo DOCK_TAG=${{ matrix.i['cpu'] }}-${{ matrix.i['os'] }}:$REL_TAG-py_std >> $GITHUB_ENV

      - name: Set up QEMU
        if: matrix.i['cpu'] == 'arm64'
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
          install: true

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ${{ env.D_DIR }}${{ matrix.i['os'] }}.Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCK_TAG }}
          platforms: linux/${{ matrix.i['cpu'] }}
          build-args: |
            BASE_IMAGE=${{ matrix.i['d_tag'] }}
            ENTRY_POINT=${{ env.D_DIR }}${{ matrix.i['os'] }}.sh
            ADD_PACKAGES=${{ matrix.i['add_packages'] }}
            OUTPUT_NAME=st_python_${{ matrix.i['cpu'] }}_${{ matrix.i['os'] }}.tar.zst

      - name: Test
        run: docker run -v /:/host --rm ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCK_TAG }}

      - uses: actions/upload-artifact@v2
        with:
          name: pythons
          path: st_pythons/*.tar.zst
          if-no-files-found: error

  draft_release:
    needs: [on_linux]
    runs-on: ubuntu-20.04
    name: Draft a release

    steps:
      - name: Collect standalone pythons
        uses: actions/download-artifact@v2
        with:
          name: pythons
          path: st_pythons

      - name: Create release draft
        uses: ncipollo/release-action@v1.8.8
        with:
          name: ${{ format('indygreg python-standalone({0})', env.REL_TAG) }}
          tag: ${{ env.REL_TAG }}
          commit: ${{ github.ref }}
          draft: true
          body: "Generated based on https://github.com/indygreg/python-build-standalone/releases"
          artifacts: st_pythons/*
          token: ${{ secrets.GITHUB_TOKEN }}
          artifactErrorsFailBuild: true
