name: PyFrm install and update test

on:
  workflow_dispatch:

env:
  URL_BASE: "https://github.com/indygreg/python-build-standalone/releases/download/20211017/cpython-3.10.0"
  URL_MANY_LINUX_x86_64: "-x86_64-unknown-linux-gnu-lto-20211017T1616.tar.zst"
  URL_MANY_LINUX_aarch64: "-aarch64-unknown-linux-gnu-lto-20211017T1616.tar.zst"
  URL_MUSL_LINUX_x86_64: ""
  URL_MUSL_LINUX_aarch64: ""
  D_DIR: "./build_tools/docker/test_py_pyfrm_basic/"
  D_EXT: ".Dockerfile"

jobs:
  on_linux:
    strategy:
      fail-fast: true
      matrix:
        i: [ { "os": "debian", "ver": "10.11", "arch": "amd64", "ep_dfile": "debian" },
             { "os": "debian", "ver": "10.11", "arch": "arm64", "ep_dfile": "debian" },
             { "os": "debian", "ver": "11.2", "arch": "amd64", "ep_dfile": "debian" },
             { "os": "debian", "ver": "11.2", "arch": "arm64", "ep_dfile": "debian" },
             { "os": "ubuntu", "ver": "21.10", "arch": "amd64", "ep_dfile": "debian" },
             { "os": "ubuntu", "ver": "21.10", "arch": "arm64", "ep_dfile": "debian" },
             { "os": "ubuntu", "ver": "22.04", "arch": "amd64", "ep_dfile": "debian" },
             { "os": "ubuntu", "ver": "22.04", "arch": "arm64", "ep_dfile": "debian" },
             { "os": "centos", "ver": "7", "arch": "amd64", "ep_dfile": "centos" },
             { "os": "centos", "ver": "7", "arch": "arm64", "ep_dfile": "centos" },
             { "os": "fedora", "ver": "35", "arch": "amd64", "ep_dfile": "fedora" },
             { "os": "fedora", "ver": "35", "arch": "arm64", "ep_dfile": "fedora" },
             { "os": "amazonlinux", "ver": "latest", "arch": "amd64", "ep_dfile": "amazon" },
             { "os": "amazonlinux", "ver": "latest", "arch": "arm64", "ep_dfile": "amazon" },
             { "os": "alpine", "ver": "3.15", "arch": "amd64", "ep_dfile": "alpine" },
#             { "os": "alpine", "ver": "3.14", "arch": "arm64", "ep_dfile": "alpine" },
             { "os": "oraclelinux", "ver": "8", "arch": "amd64", "ep_dfile": "oracle" },
             { "os": "oraclelinux", "ver": "8", "arch": "arm64", "ep_dfile": "oracle" },
             { "os": "photon", "ver": "latest", "arch": "amd64", "ep_dfile": "photon" } ]
#             { "os": "photon", "ver": "latest", "arch": "arm64", "ep_dfile": "photon" } ]
    runs-on: ubuntu-latest
    name: ðŸ â€¢ ${{ matrix.i['os'] }} â€¢ ${{ matrix.i['ver'] }} â€¢ ${{ matrix.i['arch'] }}
    env:
      KEY_HEAD: ${{ matrix.i['os'] }}-${{ matrix.i['ver'] }}-${{ matrix.i['arch'] }}-cpa_pyfrm_test_sfinst
      D_TAG: ${{ matrix.i['os'] }}-${{ matrix.i['ver'] }}-${{ matrix.i['arch'] }}:cpa_pyfrm_test_sfinst

    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        if: matrix.i['arch'] == 'arm64'
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Put standalone url(manylinux-x86_64)
        if: matrix.i['os'] != 'alpine' && matrix.i['arch'] == 'amd64'
        run: echo SP_URL="$URL_BASE$URL_MANY_LINUX_x86_64" >> $GITHUB_ENV

      - name: Put standalone url(manylinux-aarch64)
        if: matrix.i['os'] != 'alpine' && matrix.i['arch'] == 'arm64'
        run: echo SP_URL="$URL_BASE$URL_MANY_LINUX_aarch64" >> $GITHUB_ENV

      - name: Put standalone url(musllinux-x86_64)
        if: matrix.i['os'] == 'alpine' && matrix.i['arch'] == 'amd64'
        run: echo SP_URL="$URL_BASE$URL_MUSL_LINUX_x86_64" >> $GITHUB_ENV

      - name: Put standalone url(musllinux-aarch64)
        if: matrix.i['os'] == 'alpine' && matrix.i['arch'] == 'arm64'
        run: echo SP_URL="$URL_BASE$URL_MUSL_LINUX_aarch64" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ env.KEY_HEAD }}-${{ hashFiles(format('{0}{1}.*', env.D_DIR, matrix.i['ep_dfile'])) }}

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ${{ format('{0}{1}{2}', env.D_DIR,  matrix.i['ep_dfile'], env.D_EXT) }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.D_TAG }}
          platforms: linux/${{ matrix.i['arch'] }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          build-args: |
            BASE_IMAGE=${{ matrix.i['os'] }}:${{ matrix.i['ver'] }}
            ENTRY_POINT=${{ env.D_DIR }}${{ matrix.i['ep_dfile'] }}.sh
            SP_URL=${{ env.SP_URL }}

      - name: Temp fix - Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Test
        run: docker run -v /:/host --rm ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.D_TAG }}
